### ISSUE TITLE
Pregunta 1: Outputs esperados

### ISSUE THREAD

**Issue by SGhostToast** [PUC-IIC2283/Dudas-Tareas#10]
Hola!

Me pasa que al resolver los ejemplos de la pregunta 1 a mano, los resultados no me calzan con los outputs esperados, entonces quería preguntar si estoy entendiendo mal el enunciado o si hay un error en los outputs esperados.

Les dejo una hojita de excel que hice para asegurarme de no estar contando mal.
![Screenshot 2024-09-23 123139](https://github.com/user-attachments/assets/f1d7fe65-6a43-4f6a-ae91-1ff6483f9758)

**Comment by SGhostToast** [comment]
Sobre todo pregunto porque los outputs esperados tienen sentido si en realidad se desea eliminar duplicados de manera que solo queden valores únicos, entonces no se cual es el approach esperado.

**Comment by OrregoSilva** [comment]
Hola!
Hay que contar cuantos valores aparecen dentro de las columnas consultadas, si hay alguno que aparece más de una vez, solo cuenta la primera aparición. Siguiendo el primer ejemplo, a las 14 celdas blancas que muestras, hay que sumar que aparece el 7, el 8 y el 16, es decir, sería un total de 17,

**Comment by SGhostToast** [comment]
Perfecto, muchas gracias!
