### ISSUE TITLE
Duda parte 1 Complejidad

### ISSUE THREAD

**Issue by CarlangaUC** [PUC-IIC2283/Dudas-Tareas#12]
Hola!

Queria saber si hay algun tip o comentario que pueda ayudar para quizas entender el problema de otra manera ya que claramente se puede reducir la complejidad en cada consulta, la solución que estoy creando funciona pero es algo costosa entonces no se bien si hay algun concepto/formula que podriamos aplicar entendiendo DyC para asi reducir la complejidad.

**Comment by OrregoSilva** [comment]
Hola!
El problema 1, si bien se plantea como una matriz, también puede ser visto como una sola recta, donde empezamos ver cuantos números están un cierto rango por encima a los dados iniciales, esto puede ilustrarse en la siguiente imagen que muestra la primera consulta del primer testcase.
En este caso, los números indicados por flechas son los valores originales del arreglo, y como la consulta es de 0 a 3, marcamos cuáles son los números que están entre 0 y 3 unidades más adelante, indicado por los intervalos rojos, finalmente al lado se muestran cuáles son los 17 números alcanzados por estos rangos.
Lo único que podría agregar como _hint_, es que existen 2 tipos de rangos, los cuales son los que se encuentran solapados y los que no, y cada conjunto tiene una manera distinta de calcularse, como hacerlo, y como hacerlo de forma eficiente es el desafío de la pregunta, por ende no puedo decirlo.
Espero que esto te sirva de ayuda!
![image](https://github.com/user-attachments/assets/06c1f564-1dfa-407c-95d5-c76dcddcb3d5)
