### ISSUE TITLE
TIempo print P1

### ISSUE THREAD

**Issue by cristobalSaravia** [PUC-IIC2283/Dudas-Tareas#16]
Hola, tengo una duda sobre la pregunta 1. Mi programa para el test case ultra le toma casi 0.9 segundos solo en imprimir el resultado, y no he encontrado alguna otra forma para reducir este tiempo además de hacer solo un print para todo el programa y utilizar sys.stdout.write(). ¿Hay algún otro método para disminuir el tiempo de imprimir el resultado o este tiempo es lo que normalmente debería tomar para esta instancia del problema?

**Comment by OrregoSilva** [comment]
Hola!
Revisa la issue #13, el tiempo de print al final no será significativo para la corrección.
