### ISSUE TITLE
[P2] Simetría en las matrices [resuelta no se leer tenía sueño]

### ISSUE THREAD

**Issue by drcid98** [PUC-IIC2283/Dudas-Tareas#2]
Hola! las matrices de adyacencia de la pregunta 2 serán siempre simétricas? en otras palabras, el grafo es dirigido? podríamos, por ejemplo, tener una matriz del siguiente estilo?:

0 1 1 1
1 0 0 2
0 0 0 0
0 2 0 0

La pregunta es dado que no se hace mención de eso en el enunciado (lo que me hace pensar que podría ser cualquier tipo de matriz), pero por otro lado, los 2 ejemplos que aparecen tienen esa simetría, por lo que me hace dudar. Gracias!

Edit: 🤡🤡🤡

**Comment by OrregoSilva** [comment]
Hola!
Siempre serán grafos no dirigidos como se indica al final de la introducción, por ende siempre serán matrices simétricas.
