### ISSUE TITLE
Descuento por entrega tardía.

### ISSUE THREAD

**Issue by PipeOlivares** [PUC-IIC2283/Dudas-Tareas#20]
Buenas,
Quería aclarar lo que leí en el programa del curso respecto a los descuentos por entregar tarde la tarea.
Mi duda particularmente es la siguiente: ¿El descuento se efectua de manera soft (te baja el máximo de nota posible) o de manera dura (es un descuento directo sobre la nota obtenida)??

Cómo acabo de lograr solucionar la p2 unos 5 minutos despues de que se acabo el plazo de la tarea, quería asegurar que entregar con el descuento no me quitará el progreso que logré con entregar esta parte bien.

Atte,

**Comment by OrregoSilva** [comment]
Hola!
Es un descuento _soft_.
Adicionalmente, revise tu caso y entregaste justo a la hora y el _commit_ alcanzo a ser recolectado, por ende no habría descuento en esta versión de tu código :)
![image](https://github.com/user-attachments/assets/37b4d598-e3a9-4f8b-9727-65654815ca95)

**Comment by PipeOlivares** [comment]
Gracias por responder al toque!
Siii en mi caso es porque no había subido aún el commit más reciente con la pregunta completada, pero ahora que caché lo del descuento soft lo haré.
Saludos!
