### ISSUE TITLE
Formato del Input para la pregunta 1

### ISSUE THREAD

**Issue by mmerkade** [PUC-IIC2283/Dudas-Tareas#21]
Hola. Tanto en los ejemplos en el enunciado como en los testcases, las líneas del input con formato `a b` que representan a la arista entre los nodos `a` y `b` cumplen con que `a < b`. Esto no se especifica en el enunciado explícitamente. ¿Podemos asumir que siempre van a estar en ese orden, o pueden haber inputs donde `a > b`?

**Comment by OrregoSilva** [comment]
Hola!
Sí, podrán asumir que se cumple que `a < b`, En unos momentos subiré una versión actualizada con esta información.

**Comment by mmerkade** [comment]
Ok, gracias!
