### ISSUE TITLE
[P2] Cota para T

### ISSUE THREAD

**Issue by c4ebt** [PUC-IIC2283/Dudas-Tareas#22]
En la pregunta 2, el tiempo límite es "1 segundo para cualquier instancia de input según las restricciones dadas". Si bien el enunciado dice que la complejidad de la solución tiene que ser $O(T F \log F)$, no se da una cota superior para el valor de $T$, por lo que actualmente no es posible testear de manera representativa el tiempo de ejecución de nuestras soluciones con respecto al peor caso teórico (ya que al no tener una cota para $T$, no sabemos cual sería su valor en el test del peor caso).

¿Podrían dar una cota superior para $T$?

Muchas gracias de antemano :)

**Comment by OrregoSilva** [comment]
Hola!
Ahora subiré una nueva versión del enunciado, la cual indicara que $1\leq T \leq 30$
