### ISSUE TITLE
[P1] Duda con recorrer el árbol

### ISSUE THREAD

**Issue by LucasReds** [PUC-IIC2283/Dudas-Tareas#23]
Cuando recorremos el árbol, tambien hay que considerar todos los posibles arboles que parten en ese nodo? Porque tener que considerar todas estas posibilidades no se me ocurre como aplicarlo con programación dinámica.

**Comment by OrregoSilva** [comment]
Al momento de recorrer el árbol, la idea es considerar los posibles sub arboles que incluyan la misma cantidad de nodos.
Por ejemplo, en un árbol binario completo de 3 niveles (7 nodos), desde la raíz voy a un hijo, el cual es un subárbol de 3 nodos, y ahí considero las opciones con solo 3 nodos, las cuales uso para calcular las opciones del padre.
