### ISSUE TITLE
[P1] Duda sobre árboles similares

### ISSUE THREAD

**Issue by raibd** [PUC-IIC2283/Dudas-Tareas#24]
Hola, tal vez no estoy entendiendo bien los testcases, pero estoy viendo los casos mostrados en Wikipedia https://es.wikipedia.org/wiki/F%C3%B3rmula_de_Cayley#/media/Archivo:Cayley's_formula_2-4.svg, para el caso de 4 nodos, y si por ejemplo elegimos la arista rojo-amarillo, solo cuento 8 árboles con esa arista de los 16 posibles, pero en el testcase de 4 nodos del enunciado el output es 9, lo mismo para el caso de dos aristas. No se si tal vez conté mal o el problema es otro.

Gracias de antemano

**Comment by OrregoSilva** [comment]
Hola!
Para contar el grado de similitud entre árboles, no es viendo cuantas veces aparece una arista específica en los demás árboles, sino que dado un árbol cualquiera, cuantas aristas en común tiene al original.
En esta imagen tome como input el primer árbol de la imagen y marque en los demás árboles las aristas (Rojo-Amarillo), (Amarillo-Verde) y (Verde-Azul), luego debajo de cada uno coloque cuantas marcas tiene y finalmente conté cuantas veces aparece el 0, 1, 2 y 3 dentro de esas marcas.

El testcase 2 correspondería a cualquiera de los árboles de la última fila, es decir, los que poseen tres nodos conectados a uno central, si realizas el mismo procedimiento anterior verás la respuesta que sale en el enunciado.

La razón de porque en este caso la respuesta es 1 7 7 1 y no 0 9 6 1 como en el test del enunciado, es que la respuesta también depende de la forma del árbol, en este caso con $N=4$ puedes notar que hay 2 tipos de árboles en la imagen

![image](https://github.com/user-attachments/assets/52d3ae3d-87cb-4cd0-b836-5adaaf39aa8b)

**Comment by raibd** [comment]
Me queda más claro, gracias
