### ISSUE TITLE
[P2] SObre posicion del area de los faroles

### ISSUE THREAD

**Issue by llambias** [PUC-IIC2283/Dudas-Tareas#25]
Hola tenia un duda, si estamos en la posición a de la calle,¿ podemos asumir que si el farol mas cercano en una posición mayor no ilumina esa posición, tampoco va a existir otro mas lejos (después) que ilumine esa posición?

**Comment by OrregoSilva** [comment]
Hola!
No se puede asumir eso, ya que más adelante podría existir un farol que tenga un radio de alcance considerablemente mayor.
