### ISSUE TITLE
Duda sobre enunciado P2

### ISSUE THREAD

**Issue by ignacio-quera** [PUC-IIC2283/Dudas-Tareas#28]
Hola, queria saber a que se refiere la letra E en el enunciado de la P2, en particular al definir el matching parcial del objetivo: 

∀j ∈ [i, i + N' − 1], ∃z, |z − j| ≤ E ∧ D<sub>Z</sub> = O<sub>j − i</sub>

Me haría sentido que fuera una F para que se ajuste al problema.

Muchas gracias de antemano.

**Comment by OrregoSilva** [comment]
Hola!
Deberia ser una `F`, el enunciado ya fue actualizado arreglando ese error.
