### ISSUE TITLE
Duda Ejemplo P2

### ISSUE THREAD

**Issue by amondinellir** [PUC-IIC2283/Dudas-Tareas#29]
Hola. Estoy confundido en la pregunta 2, ya que en el ejemplo 2, la palabra IAE no se encuentra dentro de la palabra D. No sé si está malo el ejemplo, o no entiendo bien la pregunta, porque se tiene que cumplir que la palabra O coincida con la palabra D. 

Gracias!!

**Comment by OrregoSilva** [comment]
Hola!
El factor `F` altera la manera en la cual se generan las distintas coincidencias, intenta ver como se comporta la definición de match parcial para distintos factores. Si `F=0`, estaríamos hablando del típico problema de coincidencias de strings, que es probablemente el cual entendiste, pero en este caso es una modificación del mismo.

**Comment by JoseTomasIbanez** [comment]
Hola!

Siguiendo este hilo, es posible que den una explicación detallada de alguno de los input de ejemplo? Llevo bastante tiempo tratando de comprender la intuición del a partir de los ejemplos y se me está haciendo confusa la forma de determinar los matches entre D y O. (En especial el hecho que se pida que los strings coincidan exactamente N − N' veces).

Muchas gracias de antemano

**Comment by OrregoSilva** [comment]
Hola!
Sobre el máximo de la cantidad de coincidencias posibles, puedes pensarlo como en cuantas posiciones uno puede colocar el objetivo dentro del documento sin salirse de los límites, la siguiente imagen ilustra esto con `N = 8` y `N' = 4`
![image](https://github.com/user-attachments/assets/5a7d4049-90ba-4cf6-ab81-185733c875a3)

Y sobre una coincidencia dentro de un rango `F`, considera el siguiente ejemplo, donde en un _string_ binario quiero hacer coincidir un `1` en la posición `i = 3`, notaras que en los primeros 2 casos no existe ningún `1` dentro del rango dado por `F`, pero si lo hace en el último caso

![image](https://github.com/user-attachments/assets/a9098ee0-f9e7-4d12-b945-3745a3ef304b)

La idea de esto es poder generalizarlo para todas las letras y todas las posiciones en ambos _strings_
Espero que esto te sea de ayuda.

**Comment by JoseTomasIbanez** [comment]
Perfecto, queda mucho mas claro.

Gracias!
