### ISSUE TITLE
N - N' coincidencias en P2

### ISSUE THREAD

**Issue by ManuelV03** [PUC-IIC2283/Dudas-Tareas#30]
Hola, según el enunciado de la P2, hay que encontrar el menor F tal que O coincida con D N - N' veces, pero considerando que O puede coincidir N - N' + 1 veces con D (para cualquier i entre [0, N- N'] puede haber una coincidencia) y como dicen que nos piden encontrar F para el tope de coincidencias, probablemente aquí hubo una equivocación.
Además viendo los testases para la pregunta, estos sustentan el hecho de que los outputs son el menor F tal que ocurren N - N' + 1 coincidencias.
Agradecería si se puede aclarar la situación.

**Comment by OrregoSilva** [comment]
Hola!
Si, fue un error mio, ya subi una version actualizada, gracias por avisar!
