### ISSUE TITLE
Intuición para inputs de ejemplo P2

### ISSUE THREAD

**Issue by JoseTomasIbanez** [PUC-IIC2283/Dudas-Tareas#31]
Hola!

El otro día subí esta pregunta en el hilo de otra issue, así que quizás no fue revisada. En esa pedía si era posible que den una explicación detallada de alguno de los input de ejemplo? Llevo bastante tiempo tratando de comprender la intuición del a partir de los ejemplos y se me está haciendo confusa la forma de determinar los matches entre D y O. (En especial el hecho que se pida que los strings coincidan exactamente N − N' +1 veces).

Muchas gracias de antemano

_Originally posted by @JoseTomasIbanez in https://github.com/PUC-IIC2283/Dudas-Tareas/issues/29#issuecomment-2495741275_

**Comment by OrregoSilva** [comment]
Respondida
