### ISSUE TITLE
Duda sobre conteo de caminos de largo determinado

### ISSUE THREAD

**Issue by tcouso** [PUC-IIC2283/Dudas-Tareas#4]
Hola!

En la pregunta 2, tengo una duda sobre la interpretación del resultado. Para el testcase que se nos entrega:

Input de ejemplo 1
4
0 1 1 1
1 0 0 2
1 0 0 0
1 2 0 0
2
1
2
Output de ejemplo 1
10
28

Me causa dudas que el número de caminos de largo 2 sean 28, pues al revisar la matriz a mano, me dan 14 caminos. En ese sentido, no estoy seguro de si habrá sido un error, o si estoy entendiendo algo diferente por caminos de largo 2. Cualquier clarificación se agradece mucho. Saludos!

**Comment by OrregoSilva** [comment]
Hola!
Te comparto un dibujo que realice hace un tiempo ilustrando los 28 caminos de largo 2 existentes en ese grafo.
En este caso, el nodo relleno de azul es el inicial, mientras que el punto negro indica el final, el camino en cada la flecha celeste seguida de la flecha roja.
Notarás que hay caminos que usan 2 veces la misma arista, y otros que siguen la misma secuencia de nodos, pero de diferentes formas, especialmente cuando hay 2 aristas conectando un par de nodos.
Espero que esto te pueda servir para entender mejor como se obtienen todos los caminos.

![IMG_20240914_193451_875](https://github.com/user-attachments/assets/0dc93624-d949-4e2c-b025-e178c77c74b8)

**Comment by tcouso** [comment]
Perfecto! Me queda súper claro, muchas gracias :)
